// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SprintPlanner.Infrastructure.Persistence;

#nullable disable

namespace SprintPlanner.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SprintPlanner.Application.Configuration.GlobalSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ColdStartBeta")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)");

                    b.Property<decimal>("ColdStartSigmaFraction")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)");

                    b.Property<int>("DefaultSprintLengthDays")
                        .HasColumnType("integer");

                    b.Property<decimal>("EffectiveWorkCoefficient")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)");

                    b.Property<decimal>("LoadWarningThreshold")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)");

                    b.Property<int>("MinSprintsForReliableStats")
                        .HasColumnType("integer");

                    b.Property<int>("VelocityWindowSprints")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("global_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000005e7"),
                            ColdStartBeta = 1.0m,
                            ColdStartSigmaFraction = 0.3m,
                            DefaultSprintLengthDays = 10,
                            EffectiveWorkCoefficient = 0.8m,
                            LoadWarningThreshold = 0.85m,
                            MinSprintsForReliableStats = 3,
                            VelocityWindowSprints = 5
                        });
                });

            modelBuilder.Entity("SprintPlanner.Domain.Entities.BacklogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BusinessValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("DependencyIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<decimal>("EstimatedHours")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("LastDeveloperId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LockedDeveloperId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PreferredDeveloperId")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId");

                    b.HasIndex("Status");

                    b.ToTable("backlog_items", (string)null);
                });

            modelBuilder.Entity("SprintPlanner.Domain.Entities.CalendarOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AvailableHours")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId", "Date");

                    b.ToTable("calendar_overrides", (string)null);
                });

            modelBuilder.Entity("SprintPlanner.Domain.Entities.Competency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("competencies", (string)null);
                });

            modelBuilder.Entity("SprintPlanner.Domain.Entities.CompetencyRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BacklogItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("MinimumLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("BacklogItemId");

                    b.ToTable("competency_requirements", (string)null);
                });

            modelBuilder.Entity("SprintPlanner.Domain.Entities.Developer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CapacityHoursPerDay")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("developers", (string)null);
                });

            modelBuilder.Entity("SprintPlanner.Domain.Entities.DeveloperCompetency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetencyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("LevelNumeric")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId", "CompetencyId")
                        .IsUnique();

                    b.ToTable("developer_competencies", (string)null);
                });

            modelBuilder.Entity("SprintPlanner.Domain.Entities.DeveloperCompetencyHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("CompetencyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ToLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId", "CompetencyId");

                    b.ToTable("developer_competency_history", (string)null);
                });

            modelBuilder.Entity("SprintPlanner.Domain.Entities.Sprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("SelectedPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("sprints", (string)null);
                });

            modelBuilder.Entity("SprintPlanner.Domain.Entities.SprintHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ActualHours")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("EstimatedHours")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WasCompleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SprintId");

                    b.HasIndex("DeveloperId", "TaskId");

                    b.ToTable("sprint_history", (string)null);
                });

            modelBuilder.Entity("SprintPlanner.Domain.Entities.SprintPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Metrics")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid");

                    b.Property<string>("Warnings")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Weights")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("SprintId");

                    b.ToTable("sprint_plans", (string)null);
                });

            modelBuilder.Entity("SprintPlanner.Domain.Entities.TaskAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AdjustedHours")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<bool>("ContinuityBonus")
                        .HasColumnType("boolean");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("EstimatedHours")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<bool>("IsOnCriticalPath")
                        .HasColumnType("boolean");

                    b.Property<decimal>("SkillFitScore")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)");

                    b.Property<Guid>("SprintPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SprintPlanId");

                    b.ToTable("task_assignments", (string)null);
                });

            modelBuilder.Entity("SprintPlanner.Domain.Entities.CalendarOverride", b =>
                {
                    b.HasOne("SprintPlanner.Domain.Entities.Developer", null)
                        .WithMany("CalendarOverrides")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SprintPlanner.Domain.Entities.CompetencyRequirement", b =>
                {
                    b.HasOne("SprintPlanner.Domain.Entities.BacklogItem", null)
                        .WithMany("RequiredCompetencies")
                        .HasForeignKey("BacklogItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SprintPlanner.Domain.Entities.DeveloperCompetency", b =>
                {
                    b.HasOne("SprintPlanner.Domain.Entities.Developer", null)
                        .WithMany("Competencies")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SprintPlanner.Domain.Entities.SprintPlan", b =>
                {
                    b.HasOne("SprintPlanner.Domain.Entities.Sprint", null)
                        .WithMany("Plans")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SprintPlanner.Domain.Entities.TaskAssignment", b =>
                {
                    b.HasOne("SprintPlanner.Domain.Entities.SprintPlan", null)
                        .WithMany("Assignments")
                        .HasForeignKey("SprintPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SprintPlanner.Domain.Entities.BacklogItem", b =>
                {
                    b.Navigation("RequiredCompetencies");
                });

            modelBuilder.Entity("SprintPlanner.Domain.Entities.Developer", b =>
                {
                    b.Navigation("CalendarOverrides");

                    b.Navigation("Competencies");
                });

            modelBuilder.Entity("SprintPlanner.Domain.Entities.Sprint", b =>
                {
                    b.Navigation("Plans");
                });

            modelBuilder.Entity("SprintPlanner.Domain.Entities.SprintPlan", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
